### ISSUE TITLE
Generic error message

### ISSUE THREAD

**Issue by darklight9811** [test-room-7/action-update-file#12]
I'm trying to commit a file but a generic error message is being thrown

![image](https://user-images.githubusercontent.com/20667774/151769976-88a0242b-6755-4b38-8a3f-6819dee08151.png)

I don't know if the issue is the file not being found, if the repo is not being found, the branch, etc.

Github action:
``` yml
name: Update CONTRIBUTORS file

on:
  push:
    branches: [ development ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: minicli/action-contributors@v3
        name: "Update a projects CONTRIBUTORS file"
        env:
          CONTRIB_REPOSITORY: ${{ github.repository }}
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'

      - name: Commit changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: '[actions] update contributors'
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
```
