### ISSUE TITLE
Adding directory support

### ISSUE THREAD

**Issue by rimazmk** [test-room-7/action-update-file#4]
It would be nice if changing all files in a directory by specifying the directory could be supported. Right now if I have `directory/` as my `file-path` I get this error: `EISDIR: illegal operation on a directory, read`.

**Comment by alexesprit** [comment]
Yes, directories aren't supported.

I would resolve the issue by adding support for globs:
```yml
- name: Update resources
  uses: test-room-7/action-update-file@v1
  with:
    # All files from `dir` directory
    file-path: dir/*
```
